#!/bin/bash


#grid="grid 347 45.0"
#grid="grid 347 80.0"
grid="grid 247 60.0"
omega="omega 1.8 1.8"

cat <<EOF > crc-1.data
title CrC triplet 1.63 angstrom, starting orbitals
method oed
potsap
nuclei 24.0 6.0 1.63 angstrom
config 0
1 delta + . +
3 pi
8 sigma end
$grid
orbpot lda
scf 1 10 2 8 1
conv 2000
$omega 
fixorb
print 220
stop

EOF


cat <<EOF> crc-2.data
title CrC triplet 1.63 angstrom, starting potential
method dft
dft lda
nuclei 24.0 6.0 1.63 angstrom
config 0
1 delta + . +
3 pi
8 sigma end
$grid
orbpot old
scf 20 10 2 8 1
$omega 
conv 2000
fixorb
fixcoul
stop

EOF

cat <<EOF >crc-3.data
title CrC triplet 1.63 angstrom
method hf
nuclei 24.0 6.0 1.63 angstrom
config 0
1 delta + . +
3 pi
8 sigma end
$grid
orbpot noexch
scf 100 10 4 8 1
conv 2000
fixorb
fixcoul
$omega 
stop

EOF

#omega="omega 1.2 1.2"

cat <<EOF > crc-4.data
title CrC triplet 1.63 angstrom
method hf
nuclei 24.0 6.0 1.63 angstrom
config 0
1 delta + . +
3 pi
8 sigma end
$grid 
orbpot old !noexch
scf 400 10 4 8 1
conv 2000
!fixorb
!fixcoul
$omega 
stop

EOF

./xhf crc-1 crc-1       > crc-1.lst
./xhf crc-2 crc-1 crc-2 > crc-2.lst
./xhf crc-3 crc-2 crc-3 > crc-3.lst
./xhf crc-4 crc-3 crc-4 > crc-4.lst

