#!/bin/bash                                                                                                         

grid="grid 247 50.0"
grid="grid 169 45.0"

title="title AlF"
nuclei="nuclei 13.0  9.0  3.126"
omega="omega 1.8 1.8"

cat <<EOF > alf-lda+sap-1.data
$title 
method oed
$nuclei
config 0
2 pi
7 sigma end
$grid 
orbpot lda
potsap
scf 0 10 14 14 1
print 220
stop
EOF

cat <<EOF > alf-lda+sap-2.data
$title 
method dft
dft lda
$nuclei 
config 0
2 pi
7 sigma end
$grid 
orbpot old !lda
scf 2 10 4 14 1
fixorb
print 220
stop

EOF

cat <<EOF > alf-lda+sap-3.data
$title 
method hf
$nuclei
config 0
2 pi
7 sigma end
$grid 
orbpot noexch ! old !lda
scf 200 10 4 14 1
$omega
fixorb
fixcoul
stop

EOF


cat <<EOF > alf-lda+sap-4.data
$title 
method hf
$nuclei
config 0
2 pi
7 sigma end
$grid  
orbpot old
scf 200 10 4 14 1
!fixorb
!fixcoul
stop

EOF

./xhf alf-lda+sap-1 alf-lda+sap-1               > alf-lda+sap-1.lst
./xhf alf-lda+sap-2 alf-lda+sap-1 alf-lda+sap-2 > alf-lda+sap-2.lst
./xhf alf-lda+sap-3 alf-lda+sap-2 alf-lda+sap-3 > alf-lda+sap-3.lst
./xhf alf-lda+sap-4 alf-lda+sap-3 alf-lda+sap-4 > alf-lda+sap-4.lst

